### PR TITLE
Travis:add tests for more gcc versions

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
marked wip, gcc 5 test fails

**Comment by andy5995** [comment]
tests passed; this PR should definitely be squashed when merging.

**Comment by mathusummut** [comment]
@andy5995 shall we merge?

**Comment by andy5995** [comment]
I haven't got the clang-6.0 test to pass yet. The same set-up works on this repo https://travis-ci.org/solbu/hldig/builds/422823224 

I'm not sure why that is yet. There must be a difference somewhere. If you look at the travis log, the problem is not the build, but just finding clang-6.0. Looks like it's not adding the llvm repo that's specified on https://github.com/ZetaGlest/zetaglest-source/blob/8a3e0076f9a993de357ac985aa9b2a84ea41427d/.travis-before_install.sh#L60

**Pull request merged**
