### PR TITLE
remove miniz and zlib from libzetaglest

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by mathusummut** [comment]
Sorry @andy, this is a waste of time :/ I won’t be changing the build system on Windows every time you just impulsively decide to move files around without gaining anything.

**Comment by andy5995** [comment]
>Sorry @andy, this is a waste of time :/

I don't agree, but ok. I'll close the PR.

**Comment by mathusummut** [comment]
You can put up a ticket and have someone else do it, if you want.

**Comment by andy5995** [comment]
>You can put up a ticket and have someone else do it, if you want.

Nah, if you think it's waste of time, not much point in that, but thanks.

I'd suggest reverting the libircclient changes; there's not really any reason to have only one external lib there, when others are located elsewhere.

**Comment by mathusummut** [comment]
Let me test something.

**Pull request merged**
