### PR TITLE
The new build system for Windows

### PR DESCRIPTION
**Pull request by mathusummut**

### CODE REVIEW

**Comment by mathusummut** [comment]
I'm not sure about this yet...how should we tackle this? Basically there are 2 new folders in /mk which are windows32 and windows64, and together they total around 6GB. We probably shoudn't merge them into the main code repository, so how should we go about it?

**Comment by andy5995** [comment]
Using submodules will help prevent users from having to download more then they need.

Here's a demo of what I have in mind (submodules)

https://github.com/ZetaGlest/zetaglest-source/tree/develop/mk

Any questions or comments?

**Comment by andy5995** [comment]
Were there any files outside of windows32 or ..64 that were changed? If so, could you submit them in a separate pull request?

**Comment by mathusummut** [comment]
No files on the outside were changed :)

**Pull request closed without merging**
