### PR TITLE
[wip] ai:fix styling

### PR DESCRIPTION
**Pull request by andy5995**
This reformats the files using `indent -i2 -nut -kr -bl -bli0 -ppi3
-nbfde -nbfda -nce`

### CODE REVIEW

**Comment by andy5995** [comment]
Oh, I see now it's still breaking the line after the function type

**Comment by Jammyjamjamman** [comment]
Was this fixed in https://github.com/ZetaGlest/zetaglest-source/commit/b6a891d6c13d5eee345a474c30eba473613f4eee?

**Comment by andy5995** [comment]
>Was this fixed in b6a891d?

I double-checked. That PR only includes files in the 'types' directory.

**Comment by andy5995** [comment]
Oh, I see it's failing a check though. I'll take care of it right now.

**Pull request closed without merging**
