### PR TITLE
updated headers in menu directory

### LINKED ISSUE #252: files in menu directory need ZetaGlest header
The source code files in this directory need the header replaced

https://github.com/ZetaGlest/zetaglest-source/tree/develop/source/glest_game/menu

Some of the files already have a ZetaGlest header. Just skip those.

This is the old header:

```
// ==============================================================
//      This file is part of Glest (www.glest.org)
//
//      Copyright (C) 2001-2008 Martiño Figueroa
//
//      You can redistribute this code and/or modify it under
//      the terms of the GNU General Public License as published
//      by the Free Software Foundation; either version 2 of the
//      License, or (at your option) any later version
// ==============================================================
```

This is the new one. For each file, be sure to change the filename at the top line.

```
//
//      filename.cpp/h:
//
//      This file is part of ZetaGlest <https://github.com/ZetaGlest>
//
//      Copyright (C) 2018  The ZetaGlest team
//
//      ZetaGlest is a fork of MegaGlest <https://megaglest.org>
//
//      This program is free software: you can redistribute it and/or modify
//      it under the terms of the GNU General Public License as published by
//      the Free Software Foundation, either version 3 of the License, or
//      (at your option) any later version.
//
//      This program is distributed in the hope that it will be useful,
//      but WITHOUT ANY WARRANTY; without even the implied warranty of
//      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//      GNU General Public License for more details.
//
//      You should have received a copy of the GNU General Public License
//      along with this program.  If not, see <https://www.gnu.org/licenses/>```

### PR DESCRIPTION
**Pull request by ronsailer**
fixes #252

### CODE REVIEW

**Comment by ronsailer** [comment]
@mathusummut Please check again, I've updated the pull request comment. This fixes #252

**Comment by mathusummut** [comment]
Ah, my bad, I'll merge.

**Comment by andy5995** [comment]
@ronsailer I'm not sure if your PR was recorded properly. You may want to double-check your email settings. One of the most common causes I've seen of this are related to contributors not having set up their email in the local git config settings.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#you-havent-added-your-local-git-commit-email-to-your-profile

**Comment by ronsailer** [comment]
@andy5995 Thanks for the concern. It was recorded :+1:

**Pull request merged**
