### PR TITLE
upgrade embedded libircclient from 1.3 to 1.10

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
Oh, the ChangeLog for libircclient can be viewed at https://github.com/ZetaGlest/zetaglest-source/pull/207/files#diff-2a35002207d9e074987b668f273e598d

**Comment by andy5995** [comment]
Failing travis osx build right because it can't find libircclient. I checked at https://formulae.brew.sh/formula/ and it's apparently not available.

I'll ask around. If anybody knows of a good solution, please let us know.

**Comment by mathusummut** [comment]
Worst case scenario would be to clone the git repository of libircclient directly like it works on Windows.

**Comment by andy5995** [comment]
I think using brew with another tap will work. That's a tap @sexybiggetje set up for one of my projects.

https://travis-ci.org/ZetaGlest/zetaglest-source/jobs/425840567#L1477

I added libircclient to it. Looks like it installed but now it's just a matter of telling ZG where to find the libs.

**Comment by andy5995** [comment]
Decided to upgrade it instead of removing it. There were some problems with building and installing from source.

https://sourceforge.net/p/libircclient/bugs/27/

https://sourceforge.net/p/libircclient/bugs/18/

**Pull request merged**
